{{- if .Values.ranger_usersync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ranger.fullname" . }}-usersync
  labels:
    {{- include "ranger.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end}}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.ranger_usersync.schedule }}
  jobTemplate:
    spec:
      timeZone: {{ .Values.ranger_usersync.timeZone}}
      backoffLimit: {{ .Values.ranger_usersync.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.ranger_usersync.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "ranger.labels" . | nindent 12 }}
            {{- if .Values.commonLabels }}
            {{- toYaml .Values.commonLabels | nindent 12 }}
            {{- end}}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "ranger.fullname" . }}
              image: "{{ .Values.ranger_usersync.image.repository }}:{{ .Values.ranger_usersync.image.tag}}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "ranger.fullname" . }}
              {{- if .Values.ranger_usersync.extraEnv }}
              env:
              {{- range .Values.ranger_usersync.extraEnv }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
              {{- end }}
              {{- end }}
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/ranger_usersync/install.properties
                  subPath: install_properties
                  readOnly: false
              resources:
                {{- toYaml .Values.ranger_usersync.resources | nindent 16 }}

          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "ranger.fullname" . }}-usersync
                defaultMode: 0777
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
{{- end }}
