{{- if .Values.servicemonitor.create -}}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "ranger.fullname" . }}
  labels:
    {{ include "ranger.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end}}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "ranger.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      port: metrics
      interval: 60s
  {{- end }}
